---
# defaults file for workstation
install_package_list:
  - vim-common
  - byobu
  - python-pip
  - strace
  - mlocate
#  - grive

install_x_package_list:
  - vim-gtk
  - shutter
  - hipchat

debian_package_list:
  - git-flow
  - aptitude

debian_x_package_list:
  - chromium-browser
  - adobe-flashplugin
  - mate-terminal

redhat_package_list:
  - gitflow
  - python27
  - python27-libs
  - python27-devel
  - python27-tools
  - json-c
  - json-c-devel
  - boost-devel
  - openssl-devel
  - libxslt
  - libcurl
  - libcurl-devel
  - http://dl.dropboxusercontent.com/u/12455712/grive-0.3.0-1.el6.xz.x86_64.rpm

redhat_x_package_list:
  - gnome-terminal

install_pip_list:

debian_pip_list:

redhat_pip_list:
  - ipcluster_tools
  - ipython-cluster-helper

update_package_list:
  - gmp

byobu_line: '[ -r /home/ec2-user/byobu/prompt ] && . /home/ec2-user/.byobu/prompt   #byobu-prompt#'

alternatives:
  -

debian_alternatives:
  - {cmd: 'editor', alt: '/usr/bin/vi'}
  - {cmd: 'gnome-www-browser', alt: '/usr/bin/chromium-browser'}
  - {cmd: 'x-www-browser', alt: '/usr/bin/chromium-browser'}

vim_plugin_git_urls:
        nerdtree:
                url:  https://github.com/scrooloose/nerdtree.git
