---
# defaults file for workstation
install_package_list:
  - vim-common
  - gnome-terminal
  - byobu
  - python-pip
  - strace
  - mlocate
  - hipchat

debian_package_list:
  - git-flow
  - aptitude

redhat_package_list:
  - gitflow

install_pip_list:

update_package_list:
  - gmp

byobu_line: '[ -r /home/ec2-user/byobu/prompt ] && . /home/ec2-user/.byobu/prompt   #byobu-prompt#'
