---
# defaults file for workstation
install_package_list:
  - vim-common
  - byobu
  - python-pip
  - strace
  - mlocate
#  - grive

install_x_package_list:
  - vim-gnome
  - vim-gui-common
  - vim-gtk
  - hipchat
  - gnome-terminal

debian_package_list:
  - git-flow
  - aptitude

debian_x_package_list:
  - chromium-browser

redhat_package_list:
  - gitflow
  - xz-libs
  - zlib-devel
  - openssl-devel
  - sqlite-devel
  - bzip2-devel

redhat_x_package_list:

install_pip_list:

debian_pip_list:

redhat_pip_list:
  - ipcluster_tools
  - ipython-cluster-helper

update_package_list:
  - gmp

byobu_line: '[ -r /home/ec2-user/byobu/prompt ] && . /home/ec2-user/.byobu/prompt   #byobu-prompt#'

alternatives:
  -

debian_alternatives:
  - {cmd: 'editor', alt: '/usr/bin/vi'}
  - {cmd: 'gnome-www-browser', alt: '/usr/bin/chromium-browser'}
  - {cmd: 'x-www-browser', alt: '/usr/bin/chromium-browser'}
