---

- name: add gmatz to sudo group
  user: name='gmatz' groups='sudo' append=yes

- name: Update packages
  apt: update_cache=yes cache_valid_time=86400
  register: cache_updated

##@#- name: Add PPAs
##@#  apt_repository: repo='{{ item }}' state=present
##@#  with_items: debian_ppa_install
##@#  register: debian_ppa

##@#- name: Update apt if necessary
##@#  apt: update_cache=yes
##@#  when: debian_ppa|changed

- name: Install Common packages
  apt: name={{ item }} state=present
  with_items: install_package_list

- name: Check for X
  command: dpkg -s x11-common
  failed_when: False
  changed_when: False
  register: xoutput

- name: Add HipChat repo
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' state=present
  when: xoutput|success 

- name: Add HipChat repo key
  apt_key: url='https://www.hipchat.com/keys/hipchat-linux.key' state=present
  when: xoutput|success 
  register: repo_added


- name: Install Common X packages
  apt: name={{ item }} state=present
  with_items: install_x_package_list
  when: xoutput|success 

- name: Install Debian X packages
  apt: name={{ item }} state=present
  with_items: debian_x_package_list
  when: xoutput|success 

- name: Install highly optional Debian X packages
  apt: name={{ item }} state=present force=yes
  with_items: optional_x_package_list
  failed_when: false
  when: xoutput|success 

- name: Install uniquely-named packages
  apt: name={{ item }} state=present force=yes
  with_items: debian_package_list

- name: Upgrade packages
  apt: upgrade=safe
  when: cache_updated|changed

- name: Download Sublime Text 3
  get_url: url=http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3065_amd64.deb
           dest=/var/cache/apt/archives/sublime-text_build-3065_amd64.deb
  when: xoutput|success 

- name: Install Sublime Text 3
  apt: deb=/var/cache/apt/archives/sublime-text_build-3065_amd64.deb
  when: xoutput|success 

- name: set Debian alternatives
  alternatives: name={{ item.cmd }} path={{ item.alt }}
  with_items: debian_alternatives

- name: set Debian X alternatives
  alternatives: name={{ item.cmd }} path={{ item.alt }}
  when: xoutput|success 
  with_items: debian_x_alternatives
