---

- name: Add HipChat repo
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' state=present

- name: Add HipChat repo key
  apt_key: url='https://www.hipchat.com/keys/hipchat-linux.key' state=present

- name: Update packages
  apt: update_cache=yes

- name: Install packages
  apt: name={{ item }} state=present
  with_items: install_package_list

- name: Install uniquely-named packages
  apt: name={{ item }} state=present
  with_items: debian_package_list

- name: Update packages
  apt: upgrade=safe
