---
# tasks file for workstation
- name: Create user gmatz
  user: name=gmatz state=present

- name: Set up authorized_keys for gmatz
  authorized_key: user=gmatz
                  key="{{ item }}"
  with_file:
    - public_keys/gmatz

#- name: Update packages
#  yum: name={{ item }} state=latest
#  with_items: update_package_list

- name: Install packages
  yum: name={{ item }} state=present
  with_items: install_package_list

- name: Install PIP packages
  pip: name={{ item }} state=present
  with_items: install_pip_list

- name: Install byobu launcher
  remote_user: gmatz
  command: byobu-launcher-install
  changed_when: False

- name: Enable vi mode in .rc files
  lineinfile:
    dest=~{{ item[0] }}/{{ item[1] }}
    line="set -o vi"
    regexp="^set -o vi"
  with_nested:
    - [ 'root', 'gmatz' ]
    - [ '.bash_profile' ,'.profile' ]

- name: Enable byobu in .rc files
  lineinfile:
    dest=~{{ item[0] }}/{{ item[1] }}
    line="_byobu_sourced=1 . /usr/bin/byobu-launch"
    regexp="_byobu_sourced=1"
    insertafter=EOF
  with_nested:
    - [ 'root', 'gmatz' ]
    - [ '.bash_profile' ,'.profile' ]

- name: Enable byobu in .bashrc files
  lineinfile:
    dest=~gmatz/.bashrc
    line='{{ byobu_line }}'
    regexp="byobu-prompt"
    insertafter=EOF
