---
- name: Add HipChat repo
  copy: src=hipchat.repo dest=/etc/yum.repos.d/hipchat.repo

#- name: Update packages
#  yum: name={{ item }} state=latest
#  with_items: update_package_list

- name: Install Redhat Development Group
  yum: name='@development tools' state=present

- name: Install Redhat packages
  yum: name={{ item }} state=present
  with_items: redhat_package_list

- name: Download Python 2.7
  get_url: url='http://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz' dest=/usr/local/src
  register: download_py

- name: Unarchive Python27
  unarchive: src=/usr/local/src/Python-2.7.6.tar.xz dest=/usr/local/src creates=/usr/local/src/Python-2.7.6 
  when: download_py|success

- name: Make and Install Python27
  command: "{{ item }}"
  args:
    chdir: /usr/local/src/Python-2.7.6
    creates: /usr/local/bin/python2.7
  with_items:
    - ./configure --prefix=/usr/local
    - make
    - make altinstall
  when: download_py|success
  register: install_python

- name: Download pip27
  get_url: url=https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py dest=/usr/local/src/get-pip.py
  register: downpip27
  when: install_python|changed

- name: Install pip27
  command: /usr/local/bin/python2.7 /usr/local/src/get-pip.py
  when: downpip27|changed

- name: Install Redhat PIPs
  pip: name={{ item }} state=present executable=/usr/local/bin/pip2.7
  with_items: redhat_pip_list
