---
- name: Add HipChat repo
  copy: src=hipchat.repo dest=/etc/yum.repos.d/hipchat.repo

#- name: Update packages
#  yum: name={{ item }} state=latest
#  with_items: update_package_list

- name: Install packages
  yum: name={{ item }} state=present
  with_items: install_package_list
