---
- name: Add HipChat repo
  copy: src=hipchat.repo dest=/etc/yum.repos.d/hipchat.repo

- name: Add RepoForge repo key
  command: rpm --import http://apt.sw.be/RPM-GPG-KEY.dag.txt creates=/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmforge-dag
  register: repoforge_key

- name: Add RepoForge repo
  yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
  when: repoforge_key|changed

- name: Add rpmfusino-free repo
  yum: name=http://download1.rpmfusion.org/free/el/updates/6/i386/rpmfusion-free-release-6-1.noarch.rpm

- name: Add rpmfusion-nonfree repo
  yum: name=http://download1.rpmfusion.org/nonfree/el/updates/6/i386/rpmfusion-nonfree-release-6-1.noarch.rpm

##@#- name: Install common packages
##@#  yum: name={{ item }} state=present
##@#  with_items: install_package_list

#- name: Update packages
#  yum: name={{ item }} state=latest
#  with_items: update_package_list

- name: Install Redhat Development Group
  yum: name='@development tools' state=present

- name: Install Redhat packages
  yum: name={{ item }} state=present
  with_items: redhat_package_list

- name: Install Redhat PIPs
  pip: name={{ item }} state=present
  with_items: redhat_pip_list
