---
# tasks file for python

- name: Install Python
  apt: pkg=python state=present

- name: Install pip
  apt: pkg=python-pip state=present

- name: Install Python development packages
  apt: pkg=python-dev state=present
  when: python_development | bool

#  pip: name=virtualenv version="{{ virtualenv_version }}" state=present
- name: Install virtualenv
  pip: name=virtualenv state=present
