---
- include_vars: main.yml
# tasks file for python

- name: Install Python
  apt: pkg=python state=present
  tags: python

- name: Install pip
  apt: pkg=python-pip state=present
  tags: python

- name: Install Python development packages
  apt: pkg=python-dev state=present
  when: python_development | bool
  tags: python

- name: Install pips
  pip: name={{ item }} state=present
  with_items: "{{ pip_packages }}"
