---

- debug: msg={{ install_package_list|length > 1 }}

- name: Install Common packages
  apt: name={{ item }} state=present
  with_items: "{{ install_package_list }}"
  when: install_package_list|length > 1
  tags: ipython
 
- name: Check for X
  command: dpkg -s x11-common
  failed_when: False
  changed_when: False
  register: xoutput
  tags: ipython

- name: Install Common X packages
  apt: name={{ item }} state=present
  with_items: "{{ install_x_package_list }}"
  when: xoutput|success 
  tags: ipython

- name: Install Debian X packages
  apt: name={{ item }} state=present
  with_items: "{{ debian_x_package_list }}"
  when: xoutput|success 
  tags: ipython

- name: Install uniquely-named packages
  apt: name={{ item }} state=present
  with_items: "{{ debian_package_list }}"
  tags: ipython

- name: set Debian alternatives
  alternatives: name={{ item.cmd }} path={{ item.alt }}
  with_items: "{{ debian_alternatives }}"
  tags: ipython
