---

# tasks file for ipython

- include: Debian.yml
  when: ansible_os_family in ['Debian', 'Ubuntu','Peppermint', 'Linuxmint']
  tags: ipython

- include: Redhat.yml
  when: ansible_os_family in ['RedHat', 'Fedora','Centos']
  tags: ipython

- name: Install PIP packages
  pip: name={{ item }} state=present executable=pip2.7
  with_items: install_pip_list
  tags: ipython
